/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_ajouter_election (void);
GtkWidget* create_window_election (void);
GtkWidget* create_window_recherelect (void);
GtkWidget* create_window_calcul (void);
GtkWidget* create_menu_election (void);
