/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_ajouter_election (void)
{
  GtkWidget *window_ajouter_election;
  GtkWidget *fixed1;
  GtkObject *spinbutton1_jour_adj;
  GtkWidget *spinbutton1_jour;
  GtkObject *spinbutton1_mois_adj;
  GtkWidget *spinbutton1_mois;
  GtkObject *spinbutton1_annee_adj;
  GtkWidget *spinbutton1_annee;
  GtkWidget *entry1_ideclection;
  GtkWidget *label4;
  GtkWidget *radiobutton1_nbr1;
  GSList *radiobutton1_nbr1_group = NULL;
  GtkWidget *radiobutton1_nbr2;
  GtkWidget *radiobutton1_nbr3;
  GtkWidget *radiobutton1_nbr4;
  GtkWidget *radiobutton1_nbr5;
  GtkWidget *radiobutton1_nbr7;
  GtkWidget *radiobutton1_nbr6;
  GtkWidget *button1_ajouterElection;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *checkbutton1_confi;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label22;
  GtkWidget *label1;
  GtkWidget *label5;
  GtkWidget *entry1_gouvernorat;
  GtkWidget *label2;
  GtkWidget *label23;
  GtkWidget *comboboxentry1_munic;
  GtkWidget *label1_ajouter;
  GtkWidget *label2_donnemanq;
  GtkWidget *label3;
  GtkWidget *label1_nbrCons;
  GtkWidget *label1_modifier;
  GtkWidget *button1_ModifierElection;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label18;
  GtkWidget *button1_retourajt;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;

  window_ajouter_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_ajouter_election, 1000, 600);
  gtk_window_set_title (GTK_WINDOW (window_ajouter_election), _("ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_ajouter_election), fixed1);
  gtk_widget_set_size_request (fixed1, 800, 500);

  spinbutton1_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_jour_adj), 1, 0);
  gtk_widget_show (spinbutton1_jour);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1_jour, 248, 64);
  gtk_widget_set_size_request (spinbutton1_jour, 50, 25);

  spinbutton1_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton1_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_mois_adj), 1, 0);
  gtk_widget_show (spinbutton1_mois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1_mois, 312, 64);
  gtk_widget_set_size_request (spinbutton1_mois, 50, 25);

  spinbutton1_annee_adj = gtk_adjustment_new (2022, 2022, 2050, 1, 10, 10);
  spinbutton1_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_annee_adj), 1, 0);
  gtk_widget_show (spinbutton1_annee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1_annee, 376, 64);
  gtk_widget_set_size_request (spinbutton1_annee, 70, 25);

  entry1_ideclection = gtk_entry_new ();
  gtk_widget_show (entry1_ideclection);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_ideclection, 256, 16);
  gtk_widget_set_size_request (entry1_ideclection, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_ideclection), 8226);

  label4 = gtk_label_new (_("Nombre des habitants"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 40, 192);
  gtk_widget_set_size_request (label4, 168, 16);

  radiobutton1_nbr1 = gtk_radio_button_new_with_mnemonic (NULL, _("Jusqu'\303\240 5000 "));
  gtk_widget_show (radiobutton1_nbr1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr1, 224, 192);
  gtk_widget_set_size_request (radiobutton1_nbr1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr1), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr1));

  radiobutton1_nbr2 = gtk_radio_button_new_with_mnemonic (NULL, _("De 5001 \303\240 10 000"));
  gtk_widget_show (radiobutton1_nbr2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr2, 224, 224);
  gtk_widget_set_size_request (radiobutton1_nbr2, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr2), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr2));

  radiobutton1_nbr3 = gtk_radio_button_new_with_mnemonic (NULL, _("De 10 001 \303\240 25 000"));
  gtk_widget_show (radiobutton1_nbr3);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr3, 224, 256);
  gtk_widget_set_size_request (radiobutton1_nbr3, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr3), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr3));

  radiobutton1_nbr4 = gtk_radio_button_new_with_mnemonic (NULL, _("De 25 001 \303\240 50 000"));
  gtk_widget_show (radiobutton1_nbr4);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr4, 224, 288);
  gtk_widget_set_size_request (radiobutton1_nbr4, 176, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr4), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr4));

  radiobutton1_nbr5 = gtk_radio_button_new_with_mnemonic (NULL, _("De 50 001 \303\240 100 000"));
  gtk_widget_show (radiobutton1_nbr5);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr5, 224, 320);
  gtk_widget_set_size_request (radiobutton1_nbr5, 168, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr5), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr5));

  radiobutton1_nbr7 = gtk_radio_button_new_with_mnemonic (NULL, _("De 100 001 \303\240 500 000"));
  gtk_widget_show (radiobutton1_nbr7);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr7, 224, 352);
  gtk_widget_set_size_request (radiobutton1_nbr7, 168, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr7), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr7));

  radiobutton1_nbr6 = gtk_radio_button_new_with_mnemonic (NULL, _("Plus de 500 000"));
  gtk_widget_show (radiobutton1_nbr6);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_nbr6, 224, 376);
  gtk_widget_set_size_request (radiobutton1_nbr6, 184, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_nbr6), radiobutton1_nbr1_group);
  radiobutton1_nbr1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_nbr6));

  button1_ajouterElection = gtk_button_new ();
  gtk_widget_show (button1_ajouterElection);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ajouterElection, 576, 144);
  gtk_widget_set_size_request (button1_ajouterElection, 152, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1_ajouterElection), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  checkbutton1_confi = gtk_check_button_new ();
  gtk_widget_show (checkbutton1_confi);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1_confi, 568, 104);
  gtk_widget_set_size_request (checkbutton1_confi, 118, 24);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (checkbutton1_confi), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox15), label22, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Id"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 112, 24);
  gtk_widget_set_size_request (label1, 144, 16);

  label5 = gtk_label_new (_("Date "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 88, 72);
  gtk_widget_set_size_request (label5, 144, 16);

  entry1_gouvernorat = gtk_entry_new ();
  gtk_widget_show (entry1_gouvernorat);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_gouvernorat, 240, 112);
  gtk_widget_set_size_request (entry1_gouvernorat, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_gouvernorat), 8226);

  label2 = gtk_label_new (_("Municipalit\303\251"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 112, 152);
  gtk_widget_set_size_request (label2, 96, 32);

  label23 = gtk_label_new (_("Gouvernorat"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed1), label23, 80, 112);
  gtk_widget_set_size_request (label23, 144, 32);

  comboboxentry1_munic = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1_munic);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentry1_munic, 240, 152);
  gtk_widget_set_size_request (comboboxentry1_munic, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_munic), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_munic), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_munic), _("Ariana"));

  label1_ajouter = gtk_label_new ("");
  gtk_widget_show (label1_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), label1_ajouter, 536, 0);
  gtk_widget_set_size_request (label1_ajouter, 208, 56);

  label2_donnemanq = gtk_label_new ("");
  gtk_widget_show (label2_donnemanq);
  gtk_fixed_put (GTK_FIXED (fixed1), label2_donnemanq, 488, 48);
  gtk_widget_set_size_request (label2_donnemanq, 312, 40);

  label3 = gtk_label_new (_("Nombre de conseillers"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 40, 456);
  gtk_widget_set_size_request (label3, 168, 32);

  label1_nbrCons = gtk_label_new ("");
  gtk_widget_show (label1_nbrCons);
  gtk_fixed_put (GTK_FIXED (fixed1), label1_nbrCons, 224, 448);
  gtk_widget_set_size_request (label1_nbrCons, 152, 48);

  label1_modifier = gtk_label_new ("");
  gtk_widget_show (label1_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), label1_modifier, 536, 248);
  gtk_widget_set_size_request (label1_modifier, 216, 56);

  button1_ModifierElection = gtk_button_new ();
  gtk_widget_show (button1_ModifierElection);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ModifierElection, 576, 200);
  gtk_widget_set_size_request (button1_ModifierElection, 152, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button1_ModifierElection), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox12), label18, FALSE, FALSE, 0);

  button1_retourajt = gtk_button_new ();
  gtk_widget_show (button1_retourajt);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_retourajt, 0, 0);
  gtk_widget_set_size_request (button1_retourajt, 128, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1_retourajt), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("   Retour"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton1_nbr1, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr1, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr2, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr2, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr2_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr3, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr3, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr3_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr4, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr4, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr4_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr5, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr5, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr5_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr7, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr7, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr7_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr6, "toggled",
                    G_CALLBACK (on_radiobutton1_nbr6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_nbr6, "clicked",
                    G_CALLBACK (on_radiobutton1_nbr6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_ajouterElection, "clicked",
                    G_CALLBACK (on_button1_ajouterElection_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_confi, "toggled",
                    G_CALLBACK (on_checkbutton1_confi_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1_ModifierElection, "clicked",
                    G_CALLBACK (on_button1_ModifierElection_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_retourajt, "clicked",
                    G_CALLBACK (on_button1_retourajt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajouter_election, window_ajouter_election, "window_ajouter_election");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, spinbutton1_jour, "spinbutton1_jour");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, spinbutton1_mois, "spinbutton1_mois");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, spinbutton1_annee, "spinbutton1_annee");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, entry1_ideclection, "entry1_ideclection");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr1, "radiobutton1_nbr1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr2, "radiobutton1_nbr2");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr3, "radiobutton1_nbr3");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr4, "radiobutton1_nbr4");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr5, "radiobutton1_nbr5");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr7, "radiobutton1_nbr7");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, radiobutton1_nbr6, "radiobutton1_nbr6");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, button1_ajouterElection, "button1_ajouterElection");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, checkbutton1_confi, "checkbutton1_confi");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, image16, "image16");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label22, "label22");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, entry1_gouvernorat, "entry1_gouvernorat");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label23, "label23");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, comboboxentry1_munic, "comboboxentry1_munic");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label1_ajouter, "label1_ajouter");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label2_donnemanq, "label2_donnemanq");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label1_nbrCons, "label1_nbrCons");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label1_modifier, "label1_modifier");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, button1_ModifierElection, "button1_ModifierElection");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, button1_retourajt, "button1_retourajt");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_ajouter_election, label8, "label8");

  return window_ajouter_election;
}

GtkWidget*
create_window_election (void)
{
  GtkWidget *window_election;
  GtkWidget *fixed2;
  GtkWidget *treeview1_affElection;
  GtkWidget *hbuttonbox1;
  GtkWidget *entry2_SuppELect;
  GtkWidget *button2_affElect;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *button2_windAjouter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label14;
  GtkWidget *button2_windModif;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label13;
  GtkWidget *button2_rechElect;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *button2_SuppElect;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label12;
  GtkWidget *label2_supp;
  GtkWidget *label2_SuppEl;
  GtkWidget *button2_tachcalcul;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label24;
  GtkWidget *buttretaffich;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image26;
  GtkWidget *label38;

  window_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_election, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (window_election), _("stock"));
  gtk_window_set_position (GTK_WINDOW (window_election), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_election), 600, 300);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_election), fixed2);
  gtk_widget_set_size_request (fixed2, 672, 408);

  treeview1_affElection = gtk_tree_view_new ();
  gtk_widget_show (treeview1_affElection);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1_affElection, 182, 110);
  gtk_widget_set_size_request (treeview1_affElection, 1023, 339);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed2), hbuttonbox1, 1288, 712);
  gtk_widget_set_size_request (hbuttonbox1, 255, 29);

  entry2_SuppELect = gtk_entry_new ();
  gtk_widget_show (entry2_SuppELect);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_SuppELect, 736, 544);
  gtk_widget_set_size_request (entry2_SuppELect, 168, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_SuppELect), 8226);

  button2_affElect = gtk_button_new ();
  gtk_widget_show (button2_affElect);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_affElect, 456, 40);
  gtk_widget_set_size_request (button2_affElect, 192, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2_affElect), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("     AFFICHIER"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  button2_windAjouter = gtk_button_new ();
  gtk_widget_show (button2_windAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_windAjouter, 136, 488);
  gtk_widget_set_size_request (button2_windAjouter, 180, 50);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button2_windAjouter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("AJOUTER"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  button2_windModif = gtk_button_new ();
  gtk_widget_show (button2_windModif);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_windModif, 328, 488);
  gtk_widget_set_size_request (button2_windModif, 180, 50);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button2_windModif), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("MODIFIER"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  button2_rechElect = gtk_button_new ();
  gtk_widget_show (button2_rechElect);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_rechElect, 528, 488);
  gtk_widget_set_size_request (button2_rechElect, 180, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button2_rechElect), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("RECHERCHE"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button2_SuppElect = gtk_button_new ();
  gtk_widget_show (button2_SuppElect);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_SuppElect, 728, 488);
  gtk_widget_set_size_request (button2_SuppElect, 180, 50);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button2_SuppElect), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("SUPPRIMER"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  label2_supp = gtk_label_new ("");
  gtk_widget_show (label2_supp);
  gtk_fixed_put (GTK_FIXED (fixed2), label2_supp, 936, 504);
  gtk_widget_set_size_request (label2_supp, 264, 80);

  label2_SuppEl = gtk_label_new ("");
  gtk_widget_show (label2_SuppEl);
  gtk_fixed_put (GTK_FIXED (fixed2), label2_SuppEl, 696, 48);
  gtk_widget_set_size_request (label2_SuppEl, 232, 40);

  button2_tachcalcul = gtk_button_new ();
  gtk_widget_show (button2_tachcalcul);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_tachcalcul, 24, 232);
  gtk_widget_set_size_request (button2_tachcalcul, 144, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button2_tachcalcul), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("     Calcul"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox16), label24, FALSE, FALSE, 0);

  buttretaffich = gtk_button_new ();
  gtk_widget_show (buttretaffich);
  gtk_fixed_put (GTK_FIXED (fixed2), buttretaffich, 0, 0);
  gtk_widget_set_size_request (buttretaffich, 128, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttretaffich), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image26 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox25), image26, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("   Retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox25), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1_affElection, "row_activated",
                    G_CALLBACK (on_treeview1_affElection_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button2_affElect, "clicked",
                    G_CALLBACK (on_button2_affElect_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_windAjouter, "clicked",
                    G_CALLBACK (on_button2_windAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_windModif, "clicked",
                    G_CALLBACK (on_button2_windModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_rechElect, "clicked",
                    G_CALLBACK (on_button2_rechElect_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_SuppElect, "clicked",
                    G_CALLBACK (on_button2_SuppElect_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_tachcalcul, "clicked",
                    G_CALLBACK (on_button2_tachcalcul_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttretaffich, "clicked",
                    G_CALLBACK (on_buttretaffich_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_election, window_election, "window_election");
  GLADE_HOOKUP_OBJECT (window_election, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_election, treeview1_affElection, "treeview1_affElection");
  GLADE_HOOKUP_OBJECT (window_election, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_election, entry2_SuppELect, "entry2_SuppELect");
  GLADE_HOOKUP_OBJECT (window_election, button2_affElect, "button2_affElect");
  GLADE_HOOKUP_OBJECT (window_election, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_election, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_election, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_election, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_election, button2_windAjouter, "button2_windAjouter");
  GLADE_HOOKUP_OBJECT (window_election, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_election, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_election, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_election, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_election, button2_windModif, "button2_windModif");
  GLADE_HOOKUP_OBJECT (window_election, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_election, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_election, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_election, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_election, button2_rechElect, "button2_rechElect");
  GLADE_HOOKUP_OBJECT (window_election, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_election, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_election, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_election, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_election, button2_SuppElect, "button2_SuppElect");
  GLADE_HOOKUP_OBJECT (window_election, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_election, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_election, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_election, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_election, label2_supp, "label2_supp");
  GLADE_HOOKUP_OBJECT (window_election, label2_SuppEl, "label2_SuppEl");
  GLADE_HOOKUP_OBJECT (window_election, button2_tachcalcul, "button2_tachcalcul");
  GLADE_HOOKUP_OBJECT (window_election, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window_election, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window_election, image17, "image17");
  GLADE_HOOKUP_OBJECT (window_election, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_election, buttretaffich, "buttretaffich");
  GLADE_HOOKUP_OBJECT (window_election, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window_election, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window_election, image26, "image26");
  GLADE_HOOKUP_OBJECT (window_election, label38, "label38");

  return window_election;
}

GtkWidget*
create_window_recherelect (void)
{
  GtkWidget *window_recherelect;
  GtkWidget *fixed3;
  GtkWidget *treeview1_recElect;
  GtkWidget *button3_reche;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label20;
  GtkWidget *label3_rechint;
  GtkWidget *button3_retrecher;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label21;
  GtkWidget *entry3_rechelect;

  window_recherelect = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_recherelect, 1000, 600);
  gtk_window_set_title (GTK_WINDOW (window_recherelect), _("window_recherelect"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_recherelect), fixed3);
  gtk_widget_set_size_request (fixed3, 888, 536);

  treeview1_recElect = gtk_tree_view_new ();
  gtk_widget_show (treeview1_recElect);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1_recElect, 88, 136);
  gtk_widget_set_size_request (treeview1_recElect, 800, 400);

  button3_reche = gtk_button_new ();
  gtk_widget_show (button3_reche);
  gtk_fixed_put (GTK_FIXED (fixed3), button3_reche, 288, 24);
  gtk_widget_set_size_request (button3_reche, 232, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button3_reche), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("    Rechercher"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox13), label20, FALSE, FALSE, 0);

  label3_rechint = gtk_label_new ("");
  gtk_widget_show (label3_rechint);
  gtk_fixed_put (GTK_FIXED (fixed3), label3_rechint, 288, 80);
  gtk_widget_set_size_request (label3_rechint, 240, 48);

  button3_retrecher = gtk_button_new ();
  gtk_widget_show (button3_retrecher);
  gtk_fixed_put (GTK_FIXED (fixed3), button3_retrecher, 0, 0);
  gtk_widget_set_size_request (button3_retrecher, 176, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button3_retrecher), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox14), label21, FALSE, FALSE, 0);

  entry3_rechelect = gtk_entry_new ();
  gtk_widget_show (entry3_rechelect);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3_rechelect, 528, 32);
  gtk_widget_set_size_request (entry3_rechelect, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_rechelect), 8226);

  g_signal_connect ((gpointer) treeview1_recElect, "row_activated",
                    G_CALLBACK (on_treeview1_recElect_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button3_reche, "clicked",
                    G_CALLBACK (on_button3_reche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_retrecher, "clicked",
                    G_CALLBACK (on_button3_retrecher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_recherelect, window_recherelect, "window_recherelect");
  GLADE_HOOKUP_OBJECT (window_recherelect, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_recherelect, treeview1_recElect, "treeview1_recElect");
  GLADE_HOOKUP_OBJECT (window_recherelect, button3_reche, "button3_reche");
  GLADE_HOOKUP_OBJECT (window_recherelect, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window_recherelect, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window_recherelect, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_recherelect, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_recherelect, label3_rechint, "label3_rechint");
  GLADE_HOOKUP_OBJECT (window_recherelect, button3_retrecher, "button3_retrecher");
  GLADE_HOOKUP_OBJECT (window_recherelect, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window_recherelect, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window_recherelect, image15, "image15");
  GLADE_HOOKUP_OBJECT (window_recherelect, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_recherelect, entry3_rechelect, "entry3_rechelect");

  return window_recherelect;
}

GtkWidget*
create_window_calcul (void)
{
  GtkWidget *window_calcul;
  GtkWidget *fixed4;
  GtkWidget *label25;
  GtkWidget *label4_TPE;
  GtkWidget *button4_retCAl;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image19;
  GtkWidget *label29;
  GtkWidget *button3_calculEl;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label27;
  GtkWidget *label30;
  GtkWidget *label5_femme;

  window_calcul = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_calcul), _("window1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window_calcul), fixed4);

  label25 = gtk_label_new (_("Taux de participation des \303\251lecteurs"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 72, 112);
  gtk_widget_set_size_request (label25, 304, 40);

  label4_TPE = gtk_label_new ("");
  gtk_widget_show (label4_TPE);
  gtk_fixed_put (GTK_FIXED (fixed4), label4_TPE, 384, 112);
  gtk_widget_set_size_request (label4_TPE, 96, 48);

  button4_retCAl = gtk_button_new ();
  gtk_widget_show (button4_retCAl);
  gtk_fixed_put (GTK_FIXED (fixed4), button4_retCAl, 0, 0);
  gtk_widget_set_size_request (button4_retCAl, 120, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button4_retCAl), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image19 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox18), image19, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox18), label29, FALSE, FALSE, 0);

  button3_calculEl = gtk_button_new ();
  gtk_widget_show (button3_calculEl);
  gtk_fixed_put (GTK_FIXED (fixed4), button3_calculEl, 280, 24);
  gtk_widget_set_size_request (button3_calculEl, 144, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button3_calculEl), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox17), label27, FALSE, FALSE, 0);

  label30 = gtk_label_new (_("age moyenne\n"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 56, 240);
  gtk_widget_set_size_request (label30, 376, 48);

  label5_femme = gtk_label_new ("");
  gtk_widget_show (label5_femme);
  gtk_fixed_put (GTK_FIXED (fixed4), label5_femme, 176, 296);
  gtk_widget_set_size_request (label5_femme, 144, 32);

  g_signal_connect ((gpointer) button4_retCAl, "clicked",
                    G_CALLBACK (on_button4_retCAl_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_calculEl, "clicked",
                    G_CALLBACK (on_button3_calculEl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_calcul, window_calcul, "window_calcul");
  GLADE_HOOKUP_OBJECT (window_calcul, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_calcul, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_calcul, label4_TPE, "label4_TPE");
  GLADE_HOOKUP_OBJECT (window_calcul, button4_retCAl, "button4_retCAl");
  GLADE_HOOKUP_OBJECT (window_calcul, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window_calcul, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window_calcul, image19, "image19");
  GLADE_HOOKUP_OBJECT (window_calcul, label29, "label29");
  GLADE_HOOKUP_OBJECT (window_calcul, button3_calculEl, "button3_calculEl");
  GLADE_HOOKUP_OBJECT (window_calcul, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window_calcul, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_calcul, image18, "image18");
  GLADE_HOOKUP_OBJECT (window_calcul, label27, "label27");
  GLADE_HOOKUP_OBJECT (window_calcul, label30, "label30");
  GLADE_HOOKUP_OBJECT (window_calcul, label5_femme, "label5_femme");

  return window_calcul;
}

GtkWidget*
create_menu_election (void)
{
  GtkWidget *menu_election;
  GtkWidget *fixed5;
  GtkWidget *toajout;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label32;
  GtkWidget *tomodif;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label33;
  GtkWidget *tocherch;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image22;
  GtkWidget *label34;
  GtkWidget *tostat;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image25;
  GtkWidget *label37;
  GtkWidget *tosupp;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image24;
  GtkWidget *label36;
  GtkWidget *toaffich;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label35;
  GtkWidget *label31;

  menu_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu_election), _("menuelection"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (menu_election), fixed5);

  toajout = gtk_button_new ();
  gtk_widget_show (toajout);
  gtk_fixed_put (GTK_FIXED (fixed5), toajout, 24, 128);
  gtk_widget_set_size_request (toajout, 232, 64);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (toajout), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Ajouter election"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox19), label32, FALSE, FALSE, 0);

  tomodif = gtk_button_new ();
  gtk_widget_show (tomodif);
  gtk_fixed_put (GTK_FIXED (fixed5), tomodif, 24, 208);
  gtk_widget_set_size_request (tomodif, 232, 64);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (tomodif), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Modifier election"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox20), label33, FALSE, FALSE, 0);

  tocherch = gtk_button_new ();
  gtk_widget_show (tocherch);
  gtk_fixed_put (GTK_FIXED (fixed5), tocherch, 24, 288);
  gtk_widget_set_size_request (tocherch, 232, 64);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (tocherch), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image22 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox21), image22, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox21), label34, FALSE, FALSE, 0);

  tostat = gtk_button_new ();
  gtk_widget_show (tostat);
  gtk_fixed_put (GTK_FIXED (fixed5), tostat, 344, 288);
  gtk_widget_set_size_request (tostat, 224, 64);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (tostat), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image25 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox24), image25, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("STATISTIQUES"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox24), label37, FALSE, FALSE, 0);

  tosupp = gtk_button_new ();
  gtk_widget_show (tosupp);
  gtk_fixed_put (GTK_FIXED (fixed5), tosupp, 344, 208);
  gtk_widget_set_size_request (tosupp, 224, 56);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (tosupp), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image24 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox23), image24, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox23), label36, FALSE, FALSE, 0);

  toaffich = gtk_button_new ();
  gtk_widget_show (toaffich);
  gtk_fixed_put (GTK_FIXED (fixed5), toaffich, 344, 128);
  gtk_widget_set_size_request (toaffich, 224, 64);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (toaffich), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox22), label35, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("<span  font='14' weight='bold'>Gestion election</span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 136, 0);
  gtk_widget_set_size_request (label31, 304, 104);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  g_signal_connect ((gpointer) toajout, "clicked",
                    G_CALLBACK (on_toajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) tomodif, "clicked",
                    G_CALLBACK (on_tomodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) tocherch, "clicked",
                    G_CALLBACK (on_tocherch_clicked),
                    NULL);
  g_signal_connect ((gpointer) tostat, "clicked",
                    G_CALLBACK (on_tostat_clicked),
                    NULL);
  g_signal_connect ((gpointer) tosupp, "clicked",
                    G_CALLBACK (on_tosupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) toaffich, "clicked",
                    G_CALLBACK (on_toaffich_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu_election, menu_election, "menu_election");
  GLADE_HOOKUP_OBJECT (menu_election, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (menu_election, toajout, "toajout");
  GLADE_HOOKUP_OBJECT (menu_election, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (menu_election, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (menu_election, image20, "image20");
  GLADE_HOOKUP_OBJECT (menu_election, label32, "label32");
  GLADE_HOOKUP_OBJECT (menu_election, tomodif, "tomodif");
  GLADE_HOOKUP_OBJECT (menu_election, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (menu_election, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (menu_election, image21, "image21");
  GLADE_HOOKUP_OBJECT (menu_election, label33, "label33");
  GLADE_HOOKUP_OBJECT (menu_election, tocherch, "tocherch");
  GLADE_HOOKUP_OBJECT (menu_election, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (menu_election, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (menu_election, image22, "image22");
  GLADE_HOOKUP_OBJECT (menu_election, label34, "label34");
  GLADE_HOOKUP_OBJECT (menu_election, tostat, "tostat");
  GLADE_HOOKUP_OBJECT (menu_election, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (menu_election, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (menu_election, image25, "image25");
  GLADE_HOOKUP_OBJECT (menu_election, label37, "label37");
  GLADE_HOOKUP_OBJECT (menu_election, tosupp, "tosupp");
  GLADE_HOOKUP_OBJECT (menu_election, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (menu_election, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (menu_election, image24, "image24");
  GLADE_HOOKUP_OBJECT (menu_election, label36, "label36");
  GLADE_HOOKUP_OBJECT (menu_election, toaffich, "toaffich");
  GLADE_HOOKUP_OBJECT (menu_election, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (menu_election, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (menu_election, image23, "image23");
  GLADE_HOOKUP_OBJECT (menu_election, label35, "label35");
  GLADE_HOOKUP_OBJECT (menu_election, label31, "label31");

  return menu_election;
}

